version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: esun-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: esun_shop
    ports:
      - "3306:3306"
    volumes:
      - ./backend/DB:/docker-entrypoint-initdb.d
