import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import { createPinia } from 'pinia'
import App from './App.vue'
import api from './api'

vi.mock('./api', () => ({ default: { get: vi.fn(), post: vi.fn(), put: vi.fn(), delete: vi.fn() } }))
let wrapper
const button = text => wrapper.findAll('button').find(b => b.text() === text)
const deferred = () => { let resolve, reject; const promise = new Promise((a, b) => { resolve = a; reject = b }); return { promise, resolve, reject } }
const loginForm = async () => {
  await wrapper.get('input[placeholder="Email"]').setValue('member@example.com')
  await wrapper.get('input[type="password"]').setValue('password123')
}
beforeEach(async () => {
  localStorage.clear()
  vi.resetAllMocks()
  api.get.mockResolvedValue({ data: { data: [{ productId: 'P001', productName: 'Tea', price: 12.5, quantity: 5 }] } })
  wrapper = mount(App, { global: { plugins: [createPinia()] } })
  await flushPromises()
})
afterEach(() => wrapper.unmount())

describe('authentication UI', () => {
  it('shows backend login failure and permits another attempt', async () => {
    api.post.mockRejectedValue({ response: { status: 401, data: { message: '帳號或密碼錯誤' } } })
    await loginForm()
    await button('登入').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('帳號或密碼錯誤')
    expect(button('登入').attributes('disabled')).toBeUndefined()
    expect(localStorage.getItem('accessToken')).toBeNull()
  })
  it('shows fallback errors for network failure', async () => {
    api.post.mockRejectedValue(new Error('offline'))
    await loginForm()
    await button('登入').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('登入失敗')
  })
  it('validates fields before sending', async () => {
    await button('登入').trigger('click')
    expect(api.post).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('請輸入 Email 與密碼')
  })
  it('registers, persists session, clears password and logs out', async () => {
    await button('切換至註冊').trigger('click')
    await loginForm()
    api.post.mockResolvedValue({ data: { data: { token: 'jwt', email: 'member@example.com' } } })
    await button('註冊').trigger('click')
    await flushPromises()
    expect(api.post).toHaveBeenCalledWith('/auth/register', expect.objectContaining({ email: 'member@example.com' }))
    expect(wrapper.text()).toContain('註冊成功，已自動登入')
    expect(localStorage.getItem('accessToken')).toBe('jwt')
    await button('登出').trigger('click')
    expect(localStorage.getItem('accessToken')).toBeNull()
    expect(wrapper.get('input[type="password"]').element.value).toBe('')
  })
  it('holds busy state and mode until login completes, then handles expiry', async () => {
    const pending = deferred()
    api.post.mockReturnValue(pending.promise)
    await loginForm()
    await button('登入').trigger('click')
    expect(button('登入').attributes('disabled')).toBeDefined()
    expect(button('切換至註冊').attributes('disabled')).toBeDefined()
    pending.resolve({ data: { data: { token: 'jwt', email: 'member@example.com' } } })
    await flushPromises()
    expect(wrapper.text()).toContain('登入成功')
    window.dispatchEvent(new Event('auth-expired'))
    await flushPromises()
    expect(wrapper.text()).toContain('登入已失效，請重新登入')
    expect(localStorage.getItem('accessToken')).toBeNull()
  })
})

describe('shop UI', () => {
  it('loads products and calculates preview, submits once and clears cart on success', async () => {
    expect(wrapper.text()).toContain('Tea')
    await wrapper.get('tbody input').setValue(2)
    expect(wrapper.text()).toContain('總金額：25')
    const pending = deferred()
    api.post.mockReturnValue(pending.promise)
    await button('建立訂單').trigger('click')
    await button('建立訂單').trigger('click')
    expect(api.post).toHaveBeenCalledTimes(1)
    expect(button('建立訂單').attributes('disabled')).toBeDefined()
    expect(api.post).toHaveBeenCalledWith('/orders', expect.objectContaining({ requestId: expect.any(String), items: [{ productId: 'P001', quantity: 2 }] }))
    expect(api.post.mock.calls[0][1]).not.toHaveProperty('memberId')
    expect(api.post.mock.calls.at(-1)[1]).not.toHaveProperty('payStatus')
    pending.resolve({ data: { data: { orderId: 'ORDER-1' } } })
    await flushPromises()
    expect(wrapper.text()).toContain('訂單建立成功，訂單編號：ORDER-1')
    expect(wrapper.get('tbody input').element.value).toBe('0')
    expect(api.get).toHaveBeenCalledTimes(2)
  })
  it('requests a server-owned payment form and submits its fields in an ephemeral POST form', async () => {
    await wrapper.get('tbody input').setValue(1)
    api.post.mockResolvedValueOnce({ data: { data: { orderId: 'ORDER-1' } } })
    await button('建立訂單').trigger('click')
    await flushPromises()
    const submitted = {}
    const submit = vi.spyOn(HTMLFormElement.prototype, 'submit').mockImplementation(function () {
      submitted.action = this.action
      submitted.fields = Object.fromEntries([...this.querySelectorAll('input')].map(input => [input.name, input.value]))
    })
    api.post.mockResolvedValueOnce({ data: { data: { actionUrl: 'https://payment.example/checkout', fields: { MerchantID: 'merchant', TotalAmount: '13', CheckMacValue: 'signature' } } } })
    await button('前往付款').trigger('click')
    await flushPromises()
    expect(api.post).toHaveBeenLastCalledWith('/orders/ORDER-1/payment-form')
    expect(submitted).toEqual({ action: 'https://payment.example/checkout', fields: { MerchantID: 'merchant', TotalAmount: '13', CheckMacValue: 'signature' } })
    expect(submitted.fields).not.toHaveProperty('HashKey')
    submit.mockRestore()
  })
  it('retries a lost response with the original request after cart and products change', async () => {
    await wrapper.get('tbody input').setValue(2)
    api.post.mockRejectedValueOnce(new Error('lost response'))
    await button('建立訂單').trigger('click')
    await flushPromises()
    const original = structuredClone(api.post.mock.calls[0][1])
    api.get.mockResolvedValue({ data: { data: [] } })
    await button('重新載入商品').trigger('click')
    await flushPromises()
    api.post.mockResolvedValue({ data: { data: { orderId: 'ORIGINAL' } } })
    await button('重試未確認訂單').trigger('click')
    await flushPromises()
    expect(api.post.mock.calls[1][1]).toEqual(original)
    expect(wrapper.text()).toContain('ORIGINAL')
  })
  it('shows definitive checkout error without keeping a retry', async () => {
    await wrapper.get('tbody input').setValue(1)
    api.post.mockRejectedValue({ response: { status: 409, data: { message: '商品庫存不足' } } })
    await button('建立訂單').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('商品庫存不足')
    expect(button('重試未確認訂單')).toBeUndefined()
  })
  it('creates a product while authenticated and refreshes listing', async () => {
    await loginForm()
    api.post.mockResolvedValue({ data: { data: { token: 'jwt', email: 'member@example.com' } } })
    await button('登入').trigger('click')
    await flushPromises()
    await wrapper.get('input[placeholder="商品編號"]').setValue('P002')
    await wrapper.get('input[placeholder="商品名稱"]').setValue('Coffee')
    await wrapper.get('input[placeholder="價格"]').setValue(20)
    await wrapper.get('input[placeholder="庫存"]').setValue(10)
    await button('新增商品').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('商品新增成功')
    expect(wrapper.get('input[placeholder="商品編號"]').element.value).toBe('')
  })
})

describe('payment return UI', () => {
  it('shows only a bounded notice after returning from the provider', async () => {
    wrapper.unmount()
    history.replaceState({}, '', '/?RtnCode=1&MerchantTradeNo=untrusted')
    wrapper = mount(App, { global: { plugins: [createPinia()] } })
    await flushPromises()
    expect(wrapper.text()).toContain('已從付款頁返回；付款結果仍以系統收到並驗證的通知為準。')
    expect(api.post).not.toHaveBeenCalled()
    history.replaceState({}, '', '/')
  })
})
